env: "local" # local, dev, prod
storage_path: "postgresql://postgres:password@localhost:5432/db-name"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"
